title: Finding My Why
author: Macks Bowsure
email: mbauscher@safeharborconn.com
description: > # this means to ignore newlines until "baseurl:"
 My life ended, and this is me rebuilding it, this is my "Why".
# social links
twitter_username: @mbauscher
github_username:  @macks203

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima-theme-architect
