title: Lost to the Continental Drift  
author: Macks203
email: mbauscher@safeharborconn.com
description: > # this means to ignore newlines until "baseurl:"
 I'm lost, so i turned to the computer

# social links
twitter_username: @mbauscher  
github_username:  @macks203

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
